name: Azure Infra Deployment 

on:
 push:
   branches:
     - main
jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
      ROOT_PATH: '${{github.workspace}}/src'

# Use the bash shell 
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{env.ROOT_PATH}}
        

      - name: Terraform plan
        run:  terraform plan
        working-directory: ${{env.ROOT_PATH}}

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ${{env.ROOT_PATH}}


